spring.application.name=backend
server.port=8080

# Gemini Configuration
gemini.api.key=${GEMINI_API_KEY:}
gemini.model=gemini-2.5-flash-lite

# JWT Configuration
jwt.secret=${JWT_SECRET:mysecretkeymustbelongerthan32charactersformacsecurity}

# Database Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:mem:smartresume}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sa}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}
spring.jpa.database-platform=${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.H2Dialect}
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
